### PR TITLE
Update prometheus-client

### PR DESCRIPTION
**Pull request by SuperQ**
## 💸 TL;DR
Update to the latest prometheus-client requirement. Mainly to pick up a reduction in multi-process worker overhead[0].

[0]: https://github.com/prometheus/client_python/pull/853

## 📜 Details
[Design Doc]()

[Jira]()

## ✅ Checks

- [ ] CI tests (if present) are passing
- [ ] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Comment by maeivysea** [comment]
👋 could you link the relevant bits of the changelog? wanted to make sure the upgrade looks sane

**Review by maeivysea — CHANGES_REQUESTED** [review]
appeasing harold, feel free to re-tag

**Review by KTAtkinson — APPROVED** [review]

**Comment by SuperQ** [comment]
@maeivysea I linked to the relevant PR in the commit message/PR title.

The two full changelogs for the versions we're upgrading to:
* https://github.com/prometheus/client_python/releases/tag/v0.16.0
* https://github.com/prometheus/client_python/releases/tag/v0.15.0

**Comment by maeivysea** [comment]
apologies, i missed that in the commit message! thank you :)

**Review by maeivysea — APPROVED** [review]

**Review by KTAtkinson — APPROVED** [review]

**Pull request merged**
