### PR TITLE
Add info fields to TTransportException

### PR DESCRIPTION
**Pull request by foreverest**
Something like this would be useful. This is not the full PR but just a proposal to discuss.

### CODE REVIEW

**Comment by spladug** [comment]
hiya, sorry for the delay.  I just saw this. (Had some poorly configured email settings for GH.com -- all fixed)

Just for my understanding, what's your intended use case for the extra fields on the exceptions?

**Comment by foreverest** [comment]
In one of the services, we found it useful to send information about these exceptions to Wavefront instead of letting them spam Sentry. There are three "sub-types" of the exception (based on `last_error`): timeout, pool exhausted, and upstream exception. In a Wavefront graph, we see a separate chart for each of the sub-types per service (`namespace`) per method ('name'). Currently, we have to parse the message text to extract that information. I thought it might be useful to preserve the three pieces of information in the exception instance.

**Comment by spladug** [comment]
got it! would it make sense to add individual subtypes for the different error cases? some come from the thrift pool and some from the client itself so there'd have to be two groups but that's not too crazy. makes it really easy to add them in try/except branches then?

**Comment by foreverest** [comment]
Yeah, and then we just re-raise `last_error` [here](https://github.com/reddit/baseplate.py/pull/427/files#diff-0e434287ad163ea2c27ebbc59e86c8d5R211), right? That would work too. But note that we'd still need to add the `namespace` and `name` fields to the exception just before re-raising.
(Sorry for delaying the response. Just got to it.)

**Comment by foreverest** [comment]
There is no great need for this.

**Pull request closed without merging**
