### PR TITLE
Add stream argument support to BaseplateSession

### PR DESCRIPTION
**Pull request by 0over**
## 💸 TL;DR
Add stream argument support to pass it to `BaseplateSession.send()`

## ✅ Checks
- [x] CI tests (if present) are passing
- [x] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Review by nsheaps — CHANGES_REQUESTED** [review]
Hey Andrii! Thanks for this contribution! Would you mind sharing a bit more how you intend on using this as well as some more pydoc for the function so folks know how to use it?

For reviewers, that kwarg translates to [this](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=stream#streaming-requests)

**Review by ghirsch-reddit — CHANGES_REQUESTED** [review]
RC'ing to appease Harold

**Comment by 0over** [comment]
> Hey Andrii! Thanks for this contribution! Would you mind sharing a bit more how you intend on using this as well as some more pydoc for the function so folks know how to use it?
> 
> For reviewers, that kwarg translates to [this](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=stream#streaming-requests)

Hey Nathan! I would like to partially read the response content using `ExternalRequestsClient`. I have to pass `stream=True` to achieve it, but this argument is not propagated to the underlying `session.send` method.

Current pydoc refers to the `requests.request` page, which explains usage of `stream` argument. We just didn't support this argument in our wrapper.

**Review by nsheaps — APPROVED** [review]
Generally I prefer that our pydoc shows what we expect for arguments, even if the upstream library supports more, so that we are aware what features are in use. The way it's currently worded also doesn't make it easy to get to the appropriate documentation. That said it's not a big enough issue to block this change, just wanted to add context as to why I originally rejected it

**Review by ghirsch-reddit — APPROVED** [review]

**Pull request merged**
