### PR TITLE
Fix baseplate-tshell for versions of ipython 5+

### PR DESCRIPTION
**Pull request by bradengroom**
Fixes https://github.com/reddit/baseplate.py/issues/245.

Tested with versions 4.0.0 and 6.5.0.

### CODE REVIEW

**Comment by bradengroom** [comment]
👓 @spladug

**Comment by spladug** [comment]
Looks pretty reasonable to me. Do we use <4.0 anywhere (r2 definitely does, but not tshell-able) and if so does it work with this change?

**Comment by bradengroom** [comment]
Just tested with versions 2.2.0 and 5.8.0 since those are in our index. It seems to work fine there.

**Comment by spladug** [comment]
Great, thank you for confirming! :fish:

**Pull request merged**
