### PR TITLE
Lowercase redis command labels

### PR DESCRIPTION
**Pull request by SuperQ**
## 💸 TL;DR
In order to make baseplate.py redis client Prometheus labels consistent with other systems / clients, lowercase the redis_command label values.

## 📜 Details
[Design Doc]()

[Jira]()

## ✅ Checks

- [x] CI tests (if present) are passing
- [x] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Comment by SuperQ** [comment]
I did some simple benchmarks of this, it only adds about 50ns to the command execute. We also do a similar `.lower()` on HTTP calls in `/baseplate/clients/requests.py`.

**Review by nsheaps — CHANGES_REQUESTED** [review]
Will approve once https://github.snooguts.net/reddit/baseplate.spec/pull/79 is merged, please re-request my review at that time

**Review by KTAtkinson — APPROVED** [review]

**Review by ghirsch-reddit — APPROVED** [review]

**Comment by bjk-reddit** [comment]
Spec update has been approved and merged.

**Review by nsheaps — APPROVED** [review]

**Comment by SuperQ** [comment]
Ping, can this be merged?

**Review by chriskuehl — APPROVED** [review]
Looks reasonable to me!

I'm planning to release a baseplate 2.6.0 final version in the next couple days (and I'd like to avoid adding any more changes to this already-large release). After that, I think it'd be a good time to start working through the backlog of baseplate PRs to see what can be merged. Let's plan to merge this in a few days once 2.6.0 is out?

**Pull request merged**
